services:
  bot:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - bot-runtime:/opt/app/.runtime

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    restart: unless-stopped
    env_file:
      - .env
    profiles: ["local-bot-api"]
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api

volumes:
  bot-runtime:
  telegram-bot-api-data:
